### PR TITLE
Properly fixed benchmarks

### LINKED ISSUE #1: Fix calculations
Arises from:
https://github.com/boa-dev/boa/pull/419

Location here:
https://github.com/boa-dev/criterion-compare-action/blob/master/main.js#L88-L116

### PR DESCRIPTION
**Pull request by Razican**
It seems that the proper commit was not appearing in some clones. I re-cloned the repo and it seems it's working now. This formula should be the correct one in all cases, not only when the master factor is 1.0.

This should definitely fix #1.

### CODE REVIEW

**Comment by HalidOdat** [comment]
> It seems that the proper commit was not appearing in some clones. I re-cloned the repo and it seems it's working now. This formula should be the correct one in all cases, not only when the master factor is 1.0.

So this fixes the benchmarks not updating, right? @Razican

**Comment by Razican** [comment]
> > It seems that the proper commit was not appearing in some clones. I re-cloned the repo and it seems it's working now. This formula should be the correct one in all cases, not only when the master factor is 1.0.
> 
> So this fixes the benchmarks not updating, right? @Razican

I hope so, yes

**Comment by HalidOdat** [comment]
> I hope so, yes

What was the problem with the benchmarks not updating?

**Comment by Razican** [comment]
> > I hope so, yes
> 
> What was the problem with the benchmarks not updating?

I have no clue. If I go to the master branch in GitHub, I see the comit, but if I clone, it's not there. There was a bug in any case. But that's something strange.

**Comment by HalidOdat** [comment]
> > > I hope so, yes
> > 
> > 
> > What was the problem with the benchmarks not updating?
> 
> I have no clue. If I go to the master branch in GitHub, I see the commit, but if I clone, it's not there. There was a bug in any case. But that's something strange.

That's strange. I just cloned and I see the commit from yesterday, I think the problem might be that we did not release a new version, could that be it? because actions have specified versions, they don't just clone master, right?

**Comment by Razican** [comment]
> > > > I hope so, yes
> > > 
> > > 
> > > What was the problem with the benchmarks not updating?
> > 
> > I have no clue. If I go to the master branch in GitHub, I see the commit, but if I clone, it's not there. There was a bug in any case. But that's something strange.
> 
> That's strange. I just cloned and I see the commit from yesterday, I think the problem might be that we did not release a new version, could that be it? because actions have specified versions, they don't just clone master, right?

In theory, we are using the `master` branch for our benchmarks, and last time it took some hours to start using the latest changes, but, who knows.

**Pull request merged**
